SystemOrganization addCategory: #RemoteServiceReplication!
SystemOrganization addCategory: #'RemoteServiceReplication-Base'!
SystemOrganization addCategory: #'RemoteServiceReplication-Coordination'!
SystemOrganization addCategory: #'RemoteServiceReplication-Exceptions'!
SystemOrganization addCategory: #'RemoteServiceReplication-Public'!
SystemOrganization addCategory: #'RemoteServiceReplication-Services'!
SystemOrganization addCategory: #'RemoteServiceReplication-Utilities'!
