SystemOrganization addCategory: #RemoteServiceReplication!
SystemOrganization addCategory: #'RemoteServiceReplication-Base'!
SystemOrganization addCategory: #'RemoteServiceReplication-Communications'!
SystemOrganization addCategory: #'RemoteServiceReplication-Exceptions'!
SystemOrganization addCategory: #'RemoteServiceReplication-Manifest'!
SystemOrganization addCategory: #'RemoteServiceReplication-Public'!
SystemOrganization addCategory: #'RemoteServiceReplication-Utilities'!
