#!/usr/bin/env bash

#
# Run this script to ensure the necessary environmental variables are configured
#
export RSR_ROOT="${ROWAN_PROJECTS_ROOT}/RemoteServiceReplication"
export TEST_ROOT="${RSR_ROOT}/test-runs/"
export PATH="${RSR_ROOT}/scripts":$PATH

mkdir -p "${TEST_ROOT}"
