"
No class-specific documentation for RsrSymbolReference, hierarchy is:
Object
  RsrObject
    RsrReference
      RsrImmediateReference
        RsrCharacterArrayReference( value)
          RsrSymbolReference

"
Class {
	#name : 'RsrSymbolReference',
	#superclass : 'RsrCharacterArrayReference',
	#category : 'RemoteServiceReplication'
}

{ #category : 'converting' }
RsrSymbolReference >> convertBytes: aByteArray [

	^(super convertBytes: aByteArray) asSymbol
]
